config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :weeds do
    member do
      get "like", to: "weeds#upvote"
      get "dislike", to: "weeds#downvote"
    end
  end
  root "weeds#index"






  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end



  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :weeds
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :weeds
end

app/models/weed.rb
class Weed < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	belongs_to :category
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weeds_controller.rb
class WeedsController < ApplicationController
	before_action :find_weed, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:category].blank?
			@weeds = Weed.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@weeds = Weed.where(category_id: @category_id).order("created_at DESC")
		end
	 
	end

	def show
	end

	def new
		@weed = current_user.weeds.build
	end

	def create
		@weed = current_user.weeds.build(weed_params)

		if @weed.save
			redirect_to @weed
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @weed.update(weed_params)
			redirect_to @weed
		else
			render "edit"
		end
	end

	def destroy
		@weed.destroy
		redirect_to root_path
	end

	def upvote
		@weed.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@weed.downvote_by current_user
		redirect_to :back
	end	

	private

	def find_weed
		@weed = Weed.find(params[:id])
	end

	def weed_params
		params.require(:weed).permit(:title, :comment, :user_id, :image, :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weeds_helper.rb
module WeedsHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Weed
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
	= csrf_meta_tags
%body
	%header
		.wrapper.clearfix
			#logo= link_to "WTOOL", root_path
			%nav
				- if user_signed_in?
					= link_to "Edit user options", edit_user_registration_path, class: "button"
					= link_to "Got new weed to share?", new_weed_path, class: "button"
				- else
					= link_to "Sign in", new_user_session_path, class: "button"
					= link_to "Sign Up", new_user_registration_path, class: "button"
	
	.wrapper
		%p.notice= notice
		%p.alert= alert
		= yield

app/views/weeds/_form.html.haml
= simple_form_for @weed do |f|
		= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"}
		= f.input :image
		%br/
		= f.input :title
		%br/
		= f.input :comment
		%br/
		= f.button :submit, class: "button"

app/views/weeds/edit.html.haml
#weed_edit
	%h1 New reliable info about your Weed ??

	= render "form"

	= link_to "Back", root_path

app/views/weeds/index.html.haml
.wrapper.clearfix	
	- if user_signed_in?
		%p#intro
			Hello
			=current_user.email
			%br/
			Share your weed experiences.
	- else
		%p#intro
			Do you like to be weeded?
			%br/
			
			Share your weed experiences with other weeders
			=link_to "here", new_weed_path
	.categories
		- Category.all.each do |category|
			= link_to category.name, weeds_path(category: category.name)
		=link_to "All", root_path
		

#weeds
	- @weeds.each do |weed|
		.weed
			.weed_image
				= link_to (image_tag weed.image.url(:medium)), weed
			.weed_content
				.title
					%h2= link_to weed.title, weed
					%p
						= weed.get_likes.size
						Likes
					%p
						= weed.get_dislikes.size
						Dislikes
				.data.clearfix
					%p.username
						Shared by
						= weed.user.email
					

app/views/weeds/new.html.haml
#weed_new
	%h1 Looks like you've got new Weed !!

	= render "form"

	= link_to "Back", root_path

app/views/weeds/show.html.haml
#weed_show
	.clearfix
		%h1= @weed.title
		-if @weed.category_id == 1
			%p Indica
		-else
			%p Sativa
		%p.username
			Shared by
			= @weed.user.email
			about
			= time_ago_in_words(@weed.created_at)
	.clearfix
		.weed_image_description
			= image_tag @weed.image.url(:medium)
		.weed_comment
			%p= @weed.comment
		.weed_data
			- if @weed.user == current_user
				= link_to "Edit", edit_weed_path(@weed), class: "data"
				= link_to "Delete", weed_path(@weed), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
				= link_to "Like", like_weed_path(@weed), method: :get
				%p	
					= @weed.get_upvotes.size
					Likes
				= link_to "Dislike", dislike_weed_path(@weed), method: :get
				%p	
					= @weed.get_downvotes.size
					Dislikes